name: Security Lab

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -la

      - name: Security test
        run: exit 1
